### PR TITLE
Fixed UI issues in Footer

### PR DESCRIPTION
**Pull request by amoghjalan**
Fixed Image tag problems in Footer.

### CODE REVIEW

**Comment by akshaaatt** [comment]
Let's add some padding to the images? @amoghjalan

**Comment by amoghjalan** [comment]
ok

**Comment by amoghjalan** [comment]
image
@akshaaatt you are talking about these images only, right?
Would 2px in right and left do the work?

**Comment by akshaaatt** [comment]
I think you could go with what works best here. And yes! @amoghjalan

**Comment by akshaaatt** [comment]
Well done, thanks! I think the homepage looks fine now. But we do need to address the Profile, Login, and Register pages.

**Comment by amoghjalan** [comment]
Will work next on them

**Pull request merged**
